version: '3'

services:
#  nginx:
#    image: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - consumer
#      - producer1
#      - producer2
#    networks:
#      - lab2network

  producer1:
    build:
      context: producer1
      no_cache: false
    env_file:
      - MSize.env
    networks:
      - lab2network

  producer2:
    build:
      context: producer2
      no_cache: false
    env_file:
      - MSize.env
    networks:
      - lab2network

  consumer:
    build:
      context: consumer
      no_cache: false
    networks:
      - lab2network
    deploy:
      resources:
        limits:
          cpus: "4"

networks:
  lab2network:
